

POST http://localhost:9527/try-post
content-Type: application/x-www-form-urlencoded

name=Bob&age=19

###
POST http://localhost:9527/try-post
content-Type: application/json

{
    "name":"Bobjson",
    "age":19
}
